<h1>About The Cooper Union</h1>

<p>Founded by inventor, industrialist and philanthropist Peter Cooper in 1859, The Cooper Union for the Advancement of Science and Art has degree-granting programs in Engineering, Art and Architecture. From its beginnings, Cooper Union was a unique institution, dedicated to founder Peter Cooper's proposition that education is the key not only to personal prosperity but to civic virtue and harmony. Today, the school is home to nearly 1,000 students and is located in the East Village of New York City.</p><br/>

<p>One of the ten most selective schools in the country, The Cooper Union is world-renowned for its academic excellence and quality education. As students, we are not only pushed to our limits in our respective fields, but are also introduced to a wide array of global topics which aim to make us better citizens of New York City and the world. We take pride in contributing to the world through our work, and many of the <a href="/projects">projects</a> our students take part in address important social and environmental issues in our city and our world.</p><br/>

<p>For over 150 years, The Cooper Union has offered full-tuition scholarships to all admitted students. This freedom from economic burden has given us the opportunity to give back to our communities, freely pursue novel ideas, and explore our passions without focusing on a paycheck. However, in light of economic troubles, on April 23 2013, our Board of Trustees announced that tuition will be charged for future incoming students.</p><br/>

<p>The purpose of this website is to show our city, country and world what The Cooper Union has offered and will continue to offer. The educational environment at our school is like no other &#8212; where students have the ability to work with equally motivated peers, a world-renowned faculty, and all in an environment that is free from debt and financial stress. As students who have experienced this environment and all it has to offer to its students, and in turn, to the world &#8212; we know that an investment in an education at The Cooper Union is an investment in future generations.</p><br/>

<p>As students, it is often difficult to explain to the world why The Cooper Union is so important. As a result, we have created this website to help us begin to tell our story. Please feel free to browse the story of The Cooper Union &#8212; as told by its students &#8212; and see for yourself how such an institution has the ability to change the world.</p>